// Import createSlice from @reduxjs/toolkit to create a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the preferences slice
const initialState = {
    theme: 'light',         // Default theme is light
    language: 'en',         // Default language is English
    notifications: true,    // Notifications are enabled by default
};

// Create a slice for preferences with createSlice
const preferencesSlice = createSlice({
    name: 'preferences',    // Name of the slice
    initialState,           // Initial state defined above
    reducers: {
        // Reducer to set the theme
        setTheme(state, action) {
            state.theme = action.payload;  // Update the theme with the payload value
        },
        // Reducer to set the language
        setLanguage(state, action) {
            state.language = action.payload;  // Update the language with the payload value
        },
        // Reducer to toggle notifications
        toggleNotification: (state) => {
            state.notifications = !state.notifications;  // Toggle the notifications boolean value
        },
    },
});

// Export the actions generated by createSlice
export const { setTheme, setLanguage, toggleNotification } = preferencesSlice.actions;

// Export the reducer to be included in the Redux store
export default preferencesSlice.reducer;
